version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      PORT: "{PORT}"
      NODE_ENV: "{production}"
      DATABASE_URL: "{DATABASE_URL}"
      ACCESS_TOKEN_SECRET_KEY: "{ACCESS_TOKEN_SECRET_KEY}"
      REFRESH_TOKEN_SECRET_KEY: "{REFRESH_TOKEN_SECRET_KEY}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./drizzle:/app/drizzle
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge